// Abusing global namespace
globalThis.flagNames = {
	"🇦🇨": { fullName: "Ascension Island", shortName: "ascension-island" },
	"🇦🇩": { fullName: "Andorra", shortName: "andorra" },
	"🇦🇪": { fullName: "United Arab Emirates", shortName: "united-arab-emirates" },
	"🇦🇫": { fullName: "Afghanistan", shortName: "afghanistan" },
	"🇦🇬": { fullName: "Antigua & Barbuda", shortName: "antigua-barbuda" },
	"🇦🇮": { fullName: "Anguilla", shortName: "anguilla" },
	"🇦🇱": { fullName: "Albania", shortName: "albania" },
	"🇦🇲": { fullName: "Armenia", shortName: "armenia" },
	"🇦🇴": { fullName: "Angola", shortName: "angola" },
	"🇦🇶": { fullName: "Antarctica", shortName: "antarctica" },
	"🇦🇷": { fullName: "Argentina", shortName: "argentina" },
	"🇦🇸": { fullName: "American Samoa", shortName: "american-samoa" },
	"🇦🇹": { fullName: "Austria", shortName: "austria" },
	"🇦🇺": { fullName: "Australia", shortName: "australia" },
	"🇦🇼": { fullName: "Aruba", shortName: "aruba" },
	"🇦🇽": { fullName: "Åland Islands", shortName: "aland-islands" },
	"🇦🇿": { fullName: "Azerbaijan", shortName: "azerbaijan" },
	"🇧🇦": { fullName: "Bosnia & Herzegovina", shortName: "bosnia-herzegovina" },
	"🇧🇧": { fullName: "Barbados", shortName: "barbados" },
	"🇧🇩": { fullName: "Bangladesh", shortName: "bangladesh" },
	"🇧🇪": { fullName: "Belgium", shortName: "belgium" },
	"🇧🇫": { fullName: "Burkina Faso", shortName: "burkina-faso" },
	"🇧🇬": { fullName: "Bulgaria", shortName: "bulgaria" },
	"🇧🇭": { fullName: "Bahrain", shortName: "bahrain" },
	"🇧🇮": { fullName: "Burundi", shortName: "burundi" },
	"🇧🇯": { fullName: "Benin", shortName: "benin" },
	"🇧🇱": { fullName: "St. Barthélemy", shortName: "st-barthelemy" },
	"🇧🇲": { fullName: "Bermuda", shortName: "bermuda" },
	"🇧🇳": { fullName: "Brunei", shortName: "brunei" },
	"🇧🇴": { fullName: "Bolivia", shortName: "bolivia" },
	"🇧🇶": { fullName: "Caribbean Netherlands", shortName: "caribbean-netherlands" },
	"🇧🇷": { fullName: "Brazil", shortName: "brazil" },
	"🇧🇸": { fullName: "Bahamas", shortName: "bahamas" },
	"🇧🇹": { fullName: "Bhutan", shortName: "bhutan" },
	"🇧🇻": { fullName: "Bouvet Island", shortName: "bouvet-island" },
	"🇧🇼": { fullName: "Botswana", shortName: "botswana" },
	"🇧🇾": { fullName: "Belarus", shortName: "belarus" },
	"🇧🇿": { fullName: "Belize", shortName: "belize" },
	"🇨🇦": { fullName: "Canada", shortName: "canada" },
	"🇨🇨": { fullName: "Cocos (Keeling) Islands", shortName: "cocos-keeling-islands" },
	"🇨🇩": { fullName: "Congo - Kinshasa", shortName: "congo-kinshasa" },
	"🇨🇫": { fullName: "Central African Republic", shortName: "central-african-republic" },
	"🇨🇬": { fullName: "Congo - Brazzaville", shortName: "congo-brazzaville" },
	"🇨🇭": { fullName: "Switzerland", shortName: "switzerland" },
	"🇨🇮": { fullName: "Côte d’Ivoire", shortName: "cote-divoire" },
	"🇨🇰": { fullName: "Cook Islands", shortName: "cook-islands" },
	"🇨🇱": { fullName: "Chile", shortName: "chile" },
	"🇨🇲": { fullName: "Cameroon", shortName: "cameroon" },
	"🇨🇳": { fullName: "China", shortName: "china" },
	"🇨🇴": { fullName: "Colombia", shortName: "colombia" },
	"🇨🇵": { fullName: "Clipperton Island", shortName: "clipperton-island" },
	"🇨🇷": { fullName: "Costa Rica", shortName: "costa-rica" },
	"🇨🇺": { fullName: "Cuba", shortName: "cuba" },
	"🇨🇻": { fullName: "Cape Verde", shortName: "cape-verde" },
	"🇨🇼": { fullName: "Curaçao", shortName: "curacao" },
	"🇨🇽": { fullName: "Christmas Island", shortName: "christmas-island" },
	"🇨🇾": { fullName: "Cyprus", shortName: "cyprus" },
	"🇨🇿": { fullName: "Czechia", shortName: "czechia" },
	"🇩🇪": { fullName: "Germany", shortName: "germany" },
	"🇩🇬": { fullName: "Diego Garcia", shortName: "diego-garcia" },
	"🇩🇯": { fullName: "Djibouti", shortName: "djibouti" },
	"🇩🇰": { fullName: "Denmark", shortName: "denmark" },
	"🇩🇲": { fullName: "Dominica", shortName: "dominica" },
	"🇩🇴": { fullName: "Dominican Republic", shortName: "dominican-republic" },
	"🇩🇿": { fullName: "Algeria", shortName: "algeria" },
	"🇪🇦": { fullName: "Ceuta & Melilla", shortName: "ceuta-melilla" },
	"🇪🇨": { fullName: "Ecuador", shortName: "ecuador" },
	"🇪🇪": { fullName: "Estonia", shortName: "estonia" },
	"🇪🇬": { fullName: "Egypt", shortName: "egypt" },
	"🇪🇭": { fullName: "Western Sahara", shortName: "western-sahara" },
	"🇪🇷": { fullName: "Eritrea", shortName: "eritrea" },
	"🇪🇸": { fullName: "Spain", shortName: "spain" },
	"🇪🇹": { fullName: "Ethiopia", shortName: "ethiopia" },
	"🇪🇺": { fullName: "European Union", shortName: "european-union" },
	"🇫🇮": { fullName: "Finland", shortName: "finland" },
	"🇫🇯": { fullName: "Fiji", shortName: "fiji" },
	"🇫🇰": { fullName: "Falkland Islands", shortName: "falkland-islands" },
	"🇫🇲": { fullName: "Micronesia", shortName: "micronesia" },
	"🇫🇴": { fullName: "Faroe Islands", shortName: "faroe-islands" },
	"🇫🇷": { fullName: "France", shortName: "france" },
	"🇬🇦": { fullName: "Gabon", shortName: "gabon" },
	"🇬🇧": { fullName: "United Kingdom", shortName: "united-kingdom" },
	"🇬🇩": { fullName: "Grenada", shortName: "grenada" },
	"🇬🇪": { fullName: "Georgia", shortName: "georgia" },
	"🇬🇫": { fullName: "French Guiana", shortName: "french-guiana" },
	"🇬🇬": { fullName: "Guernsey", shortName: "guernsey" },
	"🇬🇭": { fullName: "Ghana", shortName: "ghana" },
	"🇬🇮": { fullName: "Gibraltar", shortName: "gibraltar" },
	"🇬🇱": { fullName: "Greenland", shortName: "greenland" },
	"🇬🇲": { fullName: "Gambia", shortName: "gambia" },
	"🇬🇳": { fullName: "Guinea", shortName: "guinea" },
	"🇬🇵": { fullName: "Guadeloupe", shortName: "guadeloupe" },
	"🇬🇶": { fullName: "Equatorial Guinea", shortName: "equatorial-guinea" },
	"🇬🇷": { fullName: "Greece", shortName: "greece" },
	"🇬🇸": { fullName: "South Georgia & South Sandwich Islands", shortName: "south-georgia-south-sandwich-islands" },
	"🇬🇹": { fullName: "Guatemala", shortName: "guatemala" },
	"🇬🇺": { fullName: "Guam", shortName: "guam" },
	"🇬🇼": { fullName: "Guinea-Bissau", shortName: "guinea-bissau" },
	"🇬🇾": { fullName: "Guyana", shortName: "guyana" },
	"🇭🇰": { fullName: "Hong Kong SAR China", shortName: "hong-kong-sar-china" },
	"🇭🇲": { fullName: "Heard & McDonald Islands", shortName: "heard-mcdonald-islands" },
	"🇭🇳": { fullName: "Honduras", shortName: "honduras" },
	"🇭🇷": { fullName: "Croatia", shortName: "croatia" },
	"🇭🇹": { fullName: "Haiti", shortName: "haiti" },
	"🇭🇺": { fullName: "Hungary", shortName: "hungary" },
	"🇮🇨": { fullName: "Canary Islands", shortName: "canary-islands" },
	"🇮🇩": { fullName: "Indonesia", shortName: "indonesia" },
	"🇮🇪": { fullName: "Ireland", shortName: "ireland" },
	"🇮🇱": { fullName: "Israel", shortName: "israel" },
	"🇮🇲": { fullName: "Isle of Man", shortName: "isle-of-man" },
	"🇮🇳": { fullName: "India", shortName: "india" },
	"🇮🇴": { fullName: "British Indian Ocean Territory", shortName: "british-indian-ocean-territory" },
	"🇮🇶": { fullName: "Iraq", shortName: "iraq" },
	"🇮🇷": { fullName: "Iran", shortName: "iran" },
	"🇮🇸": { fullName: "Iceland", shortName: "iceland" },
	"🇮🇹": { fullName: "Italy", shortName: "italy" },
	"🇯🇪": { fullName: "Jersey", shortName: "jersey" },
	"🇯🇲": { fullName: "Jamaica", shortName: "jamaica" },
	"🇯🇴": { fullName: "Jordan", shortName: "jordan" },
	"🇯🇵": { fullName: "Japan", shortName: "japan" },
	"🇰🇪": { fullName: "Kenya", shortName: "kenya" },
	"🇰🇬": { fullName: "Kyrgyzstan", shortName: "kyrgyzstan" },
	"🇰🇭": { fullName: "Cambodia", shortName: "cambodia" },
	"🇰🇮": { fullName: "Kiribati", shortName: "kiribati" },
	"🇰🇲": { fullName: "Comoros", shortName: "comoros" },
	"🇰🇳": { fullName: "St. Kitts & Nevis", shortName: "st-kitts-nevis" },
	"🇰🇵": { fullName: "North Korea", shortName: "north-korea" },
	"🇰🇷": { fullName: "South Korea", shortName: "south-korea" },
	"🇰🇼": { fullName: "Kuwait", shortName: "kuwait" },
	"🇰🇾": { fullName: "Cayman Islands", shortName: "cayman-islands" },
	"🇰🇿": { fullName: "Kazakhstan", shortName: "kazakhstan" },
	"🇱🇦": { fullName: "Laos", shortName: "laos" },
	"🇱🇧": { fullName: "Lebanon", shortName: "lebanon" },
	"🇱🇨": { fullName: "St. Lucia", shortName: "st-lucia" },
	"🇱🇮": { fullName: "Liechtenstein", shortName: "liechtenstein" },
	"🇱🇰": { fullName: "Sri Lanka", shortName: "sri-lanka" },
	"🇱🇷": { fullName: "Liberia", shortName: "liberia" },
	"🇱🇸": { fullName: "Lesotho", shortName: "lesotho" },
	"🇱🇹": { fullName: "Lithuania", shortName: "lithuania" },
	"🇱🇺": { fullName: "Luxembourg", shortName: "luxembourg" },
	"🇱🇻": { fullName: "Latvia", shortName: "latvia" },
	"🇱🇾": { fullName: "Libya", shortName: "libya" },
	"🇲🇦": { fullName: "Morocco", shortName: "morocco" },
	"🇲🇨": { fullName: "Monaco", shortName: "monaco" },
	"🇲🇩": { fullName: "Moldova", shortName: "moldova" },
	"🇲🇪": { fullName: "Montenegro", shortName: "montenegro" },
	"🇲🇫": { fullName: "St. Martin", shortName: "st-martin" },
	"🇲🇬": { fullName: "Madagascar", shortName: "madagascar" },
	"🇲🇭": { fullName: "Marshall Islands", shortName: "marshall-islands" },
	"🇲🇰": { fullName: "North Macedonia", shortName: "north-macedonia" },
	"🇲🇱": { fullName: "Mali", shortName: "mali" },
	"🇲🇲": { fullName: "Myanmar (Burma)", shortName: "myanmar-burma" },
	"🇲🇳": { fullName: "Mongolia", shortName: "mongolia" },
	"🇲🇴": { fullName: "Macao Sar China", shortName: "macao-sar-china" },
	"🇲🇵": { fullName: "Northern Mariana Islands", shortName: "northern-mariana-islands" },
	"🇲🇶": { fullName: "Martinique", shortName: "martinique" },
	"🇲🇷": { fullName: "Mauritania", shortName: "mauritania" },
	"🇲🇸": { fullName: "Montserrat", shortName: "montserrat" },
	"🇲🇹": { fullName: "Malta", shortName: "malta" },
	"🇲🇺": { fullName: "Mauritius", shortName: "mauritius" },
	"🇲🇻": { fullName: "Maldives", shortName: "maldives" },
	"🇲🇼": { fullName: "Malawi", shortName: "malawi" },
	"🇲🇽": { fullName: "Mexico", shortName: "mexico" },
	"🇲🇾": { fullName: "Malaysia", shortName: "malaysia" },
	"🇲🇿": { fullName: "Mozambique", shortName: "mozambique" },
	"🇳🇦": { fullName: "Namibia", shortName: "namibia" },
	"🇳🇨": { fullName: "New Caledonia", shortName: "new-caledonia" },
	"🇳🇪": { fullName: "Niger", shortName: "niger" },
	"🇳🇫": { fullName: "Norfolk Island", shortName: "norfolk-island" },
	"🇳🇬": { fullName: "Nigeria", shortName: "nigeria" },
	"🇳🇮": { fullName: "Nicaragua", shortName: "nicaragua" },
	"🇳🇱": { fullName: "Netherlands", shortName: "netherlands" },
	"🇳🇴": { fullName: "Norway", shortName: "norway" },
	"🇳🇵": { fullName: "Nepal", shortName: "nepal" },
	"🇳🇷": { fullName: "Nauru", shortName: "nauru" },
	"🇳🇺": { fullName: "Niue", shortName: "niue" },
	"🇳🇿": { fullName: "New Zealand", shortName: "new-zealand" },
	"🇴🇲": { fullName: "Oman", shortName: "oman" },
	"🇵🇦": { fullName: "Panama", shortName: "panama" },
	"🇵🇪": { fullName: "Peru", shortName: "peru" },
	"🇵🇫": { fullName: "French Polynesia", shortName: "french-polynesia" },
	"🇵🇬": { fullName: "Papua New Guinea", shortName: "papua-new-guinea" },
	"🇵🇭": { fullName: "Philippines", shortName: "philippines" },
	"🇵🇰": { fullName: "Pakistan", shortName: "pakistan" },
	"🇵🇱": { fullName: "Poland", shortName: "poland" },
	"🇵🇲": { fullName: "St. Pierre & Miquelon", shortName: "st-pierre-miquelon" },
	"🇵🇳": { fullName: "Pitcairn Islands", shortName: "pitcairn-islands" },
	"🇵🇷": { fullName: "Puerto Rico", shortName: "puerto-rico" },
	"🇵🇸": { fullName: "Palestinian Territories", shortName: "palestinian-territories" },
	"🇵🇹": { fullName: "Portugal", shortName: "portugal" },
	"🇵🇼": { fullName: "Palau", shortName: "palau" },
	"🇵🇾": { fullName: "Paraguay", shortName: "paraguay" },
	"🇶🇦": { fullName: "Qatar", shortName: "qatar" },
	"🇷🇪": { fullName: "Réunion", shortName: "reunion" },
	"🇷🇴": { fullName: "Romania", shortName: "romania" },
	"🇷🇸": { fullName: "Serbia", shortName: "serbia" },
	"🇷🇺": { fullName: "Russia", shortName: "russia" },
	"🇷🇼": { fullName: "Rwanda", shortName: "rwanda" },
	"🇸🇦": { fullName: "Saudi Arabia", shortName: "saudi-arabia" },
	"🇸🇧": { fullName: "Solomon Islands", shortName: "solomon-islands" },
	"🇸🇨": { fullName: "Seychelles", shortName: "seychelles" },
	"🇸🇩": { fullName: "Sudan", shortName: "sudan" },
	"🇸🇪": { fullName: "Sweden", shortName: "sweden" },
	"🇸🇬": { fullName: "Singapore", shortName: "singapore" },
	"🇸🇭": { fullName: "St. Helena", shortName: "st-helena" },
	"🇸🇮": { fullName: "Slovenia", shortName: "slovenia" },
	"🇸🇯": { fullName: "Svalbard & Jan Mayen", shortName: "svalbard-jan-mayen" },
	"🇸🇰": { fullName: "Slovakia", shortName: "slovakia" },
	"🇸🇱": { fullName: "Sierra Leone", shortName: "sierra-leone" },
	"🇸🇲": { fullName: "San Marino", shortName: "san-marino" },
	"🇸🇳": { fullName: "Senegal", shortName: "senegal" },
	"🇸🇴": { fullName: "Somalia", shortName: "somalia" },
	"🇸🇷": { fullName: "Suriname", shortName: "suriname" },
	"🇸🇸": { fullName: "South Sudan", shortName: "south-sudan" },
	"🇸🇹": { fullName: "São Tomé & Príncipe", shortName: "sao-tome-principe" },
	"🇸🇻": { fullName: "El Salvador", shortName: "el-salvador" },
	"🇸🇽": { fullName: "Sint Maarten", shortName: "sint-maarten" },
	"🇸🇾": { fullName: "Syria", shortName: "syria" },
	"🇸🇿": { fullName: "Eswatini", shortName: "eswatini" },
	"🇹🇦": { fullName: "Tristan Da Cunha", shortName: "tristan-da-cunha" },
	"🇹🇨": { fullName: "Turks & Caicos Islands", shortName: "turks-caicos-islands" },
	"🇹🇩": { fullName: "Chad", shortName: "chad" },
	"🇹🇫": { fullName: "French Southern Territories", shortName: "french-southern-territories" },
	"🇹🇬": { fullName: "Togo", shortName: "togo" },
	"🇹🇭": { fullName: "Thailand", shortName: "thailand" },
	"🇹🇯": { fullName: "Tajikistan", shortName: "tajikistan" },
	"🇹🇰": { fullName: "Tokelau", shortName: "tokelau" },
	"🇹🇱": { fullName: "Timor-Leste", shortName: "timor-leste" },
	"🇹🇲": { fullName: "Turkmenistan", shortName: "turkmenistan" },
	"🇹🇳": { fullName: "Tunisia", shortName: "tunisia" },
	"🇹🇴": { fullName: "Tonga", shortName: "tonga" },
	"🇹🇷": { fullName: "Turkey", shortName: "turkey" },
	"🇹🇹": { fullName: "Trinidad & Tobago", shortName: "trinidad-tobago" },
	"🇹🇻": { fullName: "Tuvalu", shortName: "tuvalu" },
	"🇹🇼": { fullName: "Taiwan", shortName: "taiwan" },
	"🇹🇿": { fullName: "Tanzania", shortName: "tanzania" },
	"🇺🇦": { fullName: "Ukraine", shortName: "ukraine" },
	"🇺🇬": { fullName: "Uganda", shortName: "uganda" },
	"🇺🇲": { fullName: "U.S. Outlying Islands", shortName: "us-outlying-islands" },
	"🇺🇳": { fullName: "United Nations", shortName: "united-nations" },
	"🇺🇸": { fullName: "United States", shortName: "united-states" },
	"🇺🇾": { fullName: "Uruguay", shortName: "uruguay" },
	"🇺🇿": { fullName: "Uzbekistan", shortName: "uzbekistan" },
	"🇻🇦": { fullName: "Vatican City", shortName: "vatican-city" },
	"🇻🇨": { fullName: "St. Vincent & Grenadines", shortName: "st-vincent-grenadines" },
	"🇻🇪": { fullName: "Venezuela", shortName: "venezuela" },
	"🇻🇬": { fullName: "British Virgin Islands", shortName: "british-virgin-islands" },
	"🇻🇮": { fullName: "U.S. Virgin Islands", shortName: "us-virgin-islands" },
	"🇻🇳": { fullName: "Vietnam", shortName: "vietnam" },
	"🇻🇺": { fullName: "Vanuatu", shortName: "vanuatu" },
	"🇼🇫": { fullName: "Wallis & Futuna", shortName: "wallis-futuna" },
	"🇼🇸": { fullName: "Samoa", shortName: "samoa" },
	"🇽🇰": { fullName: "Kosovo", shortName: "kosovo" },
	"🇾🇪": { fullName: "Yemen", shortName: "yemen" },
	"🇾🇹": { fullName: "Mayotte", shortName: "mayotte" },
	"🇿🇦": { fullName: "South Africa", shortName: "south-africa" },
	"🇿🇲": { fullName: "Zambia", shortName: "zambia" },
	"🇿🇼": { fullName: "Zimbabwe", shortName: "zimbabwe" },

	"🏴󠁧󠁢󠁥󠁮󠁧󠁿": { fullName: "England", shortName: "england" },
	"🏴󠁧󠁢󠁳󠁣󠁴󠁿": { fullName: "Scotland", shortName: "scotland" },
	"🏴󠁧󠁢󠁷󠁬󠁳󠁿": { fullName: "Wales", shortName: "wales" }
};

// Capturing groups (*) for keys in dictionary above
//                     [ * tag latin chars   ]
let regex2CharFlag = /([\uD83C][\uDDE6-\uDDFF]){2}/g;
//                     [  black flag  ] [ * tag latin chars   ]  [  cancel tag  ]
let regexSubdivFlag = /[\uD83C][\uDFF4]([\uDB40][\uDC61-\uDC7A])+[\uDB40][\uDC7F]/g;

// Combine them all into one regex for faster comparison
let regexes = [ regex2CharFlag, regexSubdivFlag ];
globalThis.regexGeneralFlag = new RegExp(regexes.map(r => r.source).join("|"), "g");

globalThis.urlNumbers = {
	"apple": "354",
	"google": "350",
	"samsung": "349",
	"whatsapp": "352",
	"twitter": "322",
	"facebook": "355",
	"openmoji": "338"
};
